baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - /scripts

# Build settings
markdown: kramdown
