jekyll:
    image: jekyll/jekyll:pages
    command: bash -c "rm -rf ./categories/*.html && rm -rf ./tags/*.html && ./scripts/generate-categories && ./scripts/generate-tags && bundle exec jekyll serve --watch"
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
